### ISSUE TITLE
[NEW FEATURE] Any kind of network support

### ISSUE THREAD

**Issue by nicolas-rabault** [Luos-io/luos_engine#428]
# Any kind of network support
The main goal of this feature is to drastically simplify the addition of various networks’ support into the Luos engine library. Luos engine will not be limited to the Robus network layer anymore, and will be able to deal with any kind of network.
The closure of this issue will lead to the creation of a v3.0.0 release of Luos.
![image](https://user-images.githubusercontent.com/9554146/226988135-ea76b6ab-7956-4408-92e9-bb88e044fa8f.png#gh-dark-mode-only)
![image](https://user-images.githubusercontent.com/9554146/226988229-f9275276-376e-4b7b-8872-b27f7556a4ab.png#gh-light-mode-only)

## User point of view
This new version should not change anything on the service development side. A few API may be changed but services algorithm shouldn't change at all.
Users may have more options on the transportation layer side allowing them to choose different ones depending on there configuration.
Users can design there own transportation layer allowing to deal with custom one.
Transportation layer should be considered as kind of packages.

## Expected results
In the end of this project, we should have Luos services on a computer and a board able to exchange information and detect using serial communication over USB.

## Tasks : 
 - [x] Move files from Robus to IO folder (msg_alloc, filtering, reception, ...)
 - [x] Rename files functions and check for unit tests
 - [x] Check for configuration files
 - [x] Add an IO init and loop functions
 - [x] Add a phy struct gathering physical layers informations
 - [x] Simplify rx msg_allocation by adding a buffer on the phy struct
 - [x] Also use buffer to manage RX treatment out of IRQ
 - [x] Add a topology IO management function
 - [x] Create phy.h function template
     - [x] Manage init / loop interface
     - [x] Manage reception interface
     - [x] Manage detection interface
     - [x] Manage transmission interface
 - [x] Create phy interface for Robus
 - [x] Unit tests of Luos V3
 - [x] Hardware test of Luos V3
 - [x] Create phy interface for serial USB
